apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-du8v
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-du8v@sha256:77206d467084008ce7eb7055269a8715178d1883afc6db7fbc00f50a3ab9c760
        name: my-nodejs
        resources: {}
status: {}
